=== yakshadevelopment/Master-Java-Web-Services-and-REST-API-with-Spring-Boot_diffExamResult/diff_examResult/example-files/exam_result.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  targetNamespace="http://yaksha.edu/examapp" xmlns:tns="http://yaksha.edu/examapp" elementFormDefault="qualified">

<xs:element name="ShowResultRequest">
<xs:complexType>
 <xs:sequence>
  <xs:element name="roll" type="xs:int"/>
  <xs:element name="eng" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="lang" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="math" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="science" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="social-science" type="xs:int" maxOccurs="100"  minOccurs="0"/>
 </xs:sequence>
 </xs:complexType>
 </xs:element>
 
 
 <xs:element name="DisplayResultRequest">
 <xs:complexType>
 <xs:sequence>
  <xs:element name="roll" type="xs:int"/>
  <xs:element name="eng" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="lang" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="math" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="science" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="social-science" type="xs:int" maxOccurs="100"  minOccurs="0"/>
 </xs:sequence>
 </xs:complexType>
 
 </xs:element>
 
 
 <xs:element name="ShowResultResponse">
 <xs:complexType>
 <xs:sequence>
  <xs:element name="StudentResult" type="tns:Result"/>
 </xs:sequence>
 </xs:complexType>
 </xs:element>
 
 
 
 <xs:complexType name="Result">
   <xs:sequence>
  <xs:element name="roll" type="xs:int"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="eng" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="lang" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="math" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="science" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="social-science" type="xs:int" maxOccurs="100"  minOccurs="0"/>
  <xs:element name="total" type="xs:int"/>
  <xs:element name="grade" type="xs:string"/>
     </xs:sequence>
 </xs:complexType>

</xs:schema>

=== yakshadevelopment/Master-Java-Web-Services-and-REST-API-with-Spring-Boot_diffExamResult/diff_examResult/example-files/Response.xml
<?xml version="1.0" encoding="UTF-8"?>

<ShowResultResponse xmlns="http://yaksha.edu/examapp" xsi:schemaLocation="http://yaksha.edu/examapp exam_result.xsd"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<StudentResult>
<roll>5</roll>
<name>Rogers</name>
<eng>80</eng>
<lang>75</lang>
<math>90</math>
<science>80</science>
<social-science>65</social-science>
<total>390</total>
<grade>Good</grade>
</StudentResult>
</ShowResultResponse>

<!-- <AddNewStudentResponse xmlns="http://yaksha.edu/examapp" xsi:schemaLocation="http://yaksha.edu/examapp exam_result.xsd"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<roll>10</roll>
<name>Tom Walter</name>
<status>Success</status>
</AddNewStudentResponse> -->
